# Generated by Django 4.1.3 on 2022-11-30 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='modified_data',
            new_name='modified_date',
        ),
    ]
