# Generated by Django 4.1.3 on 2022-12-01 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_modified_data_product_modified_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
