# Generated by Django 4.1.3 on 2022-12-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('Colour', 'babi'), ('Size', 'size'), ('Length', 'length')], max_length=200),
        ),
    ]
