# Generated by Django 4.1.3 on 2022-12-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_variation_variation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('Colour', 'colour'), ('Size', 'size'), ('Length', 'length')], max_length=200),
        ),
    ]
