# Generated by Django 4.1.3 on 2022-12-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.CharField(default=32, max_length=200),
            preserve_default=False,
        ),
    ]
